swagger: "2.0"
info:
  description: ""
  version: "1.0.1"
  title: "Yurkas order"
host: "1c.yurkas.ru"
basePath: "/v1"
tags:
- name: "Access orders"
  description: "Доступ к заказам"
schemes:
- "https"
paths:
  /order:
    post:
      tags:
      - "Access orders"
      summary: "Создать заказ"
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Размещение заказа"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200": 
          description: "The order has already been created" 
          schema:
            $ref: "#/definitions/status"
        "201":
          description: "CREATED"
          schema:
            $ref: "#/definitions/status"
        "400":
          description: "Bad Request"
      security:
        - api_key: []
    get:
      tags:
      - "Access orders"
      summary: "Получить статус заказа"
      operationId: "getOrderById"
      produces:
      - "application/json"
      parameters:
      - name: "messageNumber"
        in: "query"
        description: "Номер заказа по которому нужно получить статус"
        required: true
        type: "integer"
        format: "int64"
      - name: "counterpartyInn"
        in: "query"
        description: "ИНН контрагента"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/status"
        "400":
          description: "Bad Request"
        "404":
          description: "Order not found"
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: apikey
    in: header
definitions:
  Order:
    title: "Заказ"
    type: "object"
    properties:
      warehouse:
        type: "string"
        description: "Склад оргранизации"
        enum:
        - "Moscow"
        - "SPB"
      organization:
        type: "string"
        description: "Название оргранизации"
        enum:
        - "Yurkas"
        - "Germes"
        - "YurkasDoors"
        - "YurkasSpb"  
      counterpartyInn:
        type: "string"
        description: "ИНН"
      messageNumber:
        type: "integer"
        format: "int64"
        description: "Номер входящего сообщения. Уникальный номер клиентской заявки."
      tradePoint:
        $ref: "#/definitions/tradePoint"  
      formOfPayment:
        $ref: "#/definitions/formOfPayment"
      goods:
        type: array
        items: 
          $ref: "#/definitions/goods"
    required:
      - warehouse
      - organization
      - counterpartyInn
      - messageNumber
      - tradePoint
      - formOfPayment
      - goods 
  status:
    title: "Статус заказа"
    type: "object"
    properties:
      status:
        $ref: "#/definitions/statuses"
  statuses:
    title: "Статусы заказа"
    type: "string"
    description: |
      * `accepted` --- Заказ принят в обработку
      * `inprogress` --- Заказ находиться в работе
      * `ready` --- Заказ готов к отгрузке
      * `closed` --- Заказ закрыт
      * `completed` --- Заказ выполнен
    enum:        
      - "accepted"        
      - "inprogress"
      - "ready"
      - "closed"
      - "completed"
  goods:
    title: "Таблица товаров"
    type: "object"
    properties:
      barcode:
        type: "string"
        description: "Штрихкод"
      count:
        type: "integer"
        format: "int64"
    required:
      - barcode
      - count
  formOfPayment:
    title: "Форма расчетов"
    type: "string"
    description: |
      * `NAL` --- оплата наличными
      * `BNAL` --- безналичная форма оплаты
    enum:        
      - "NAL"        
      - "BNAL"
  tradePoint:
    type: "object"
    title: "Кординаты торговой точки"
    description: "Кординаты торговой точки в формате [53.848776, 27.372260] [Широта, долгота]"
    properties:
      lat:
        type: "integer"
        description: "широта местоположения объекта в формате градусы – доли градусов"
      lon:
        type: "integer"
        description: "долгота местоположения объекта в формате градусы – доли градусов"
    required:
      - lat
      - Lon