swagger: '2.0'
info:
  description: ' Данный сервис предназначен для генерации и работы с заказами компании Юркас. Ключи доступа(API key) и УИД торговых точек необходимо получить у тех. специалиста.'
  version: 1.0.6
  title: Yurkas order
host: 1c-test.yurkas.ru
basePath: /v1
tags:
  - name: Access orders
    description: Доступ к заказам
schemes:
  - https
paths:
  /order:
    post:
      tags:
        - Access orders
      summary: Создать заказ
      description: ''
      operationId: placeOrder
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Размещение заказа
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: The order has already been created
          schema:
            $ref: '#/definitions/status'
        '201':
          description: CREATED
          schema:
            $ref: '#/definitions/status'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - APIKeyHeader: []
    get:
      tags:
        - Access orders
      summary: Получить статус заказа
      operationId: getOrderById
      produces:
        - application/json
      parameters:
        - name: messageNumber
          in: query
          description: Номер заказа по которому нужно получить статус
          required: true
          type: integer
          format: int64
        - name: counterpartyInn
          in: query
          description: ИНН контрагента
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/status'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Order not found
      security:
        - APIKeyHeader: []
  /price:
    get:
      tags: 
        - Access orders
      summary: Получить цену заказа
      operationId: getPrice
      produces:
        - application/json
      parameters:
        - name: messageNumber
          in: query
          description: Номер заказа по которому нужно получить статус
          required: true
          type: integer
          format: int64
        - name: counterpartyInn
          in: query
          description: ИНН контрагента
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
             $ref: '#/definitions/responsePrice'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Order not found
      security:
        - APIKeyHeader: []
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: apikey
definitions:
  Order:
    title: Заказ
    type: object
    properties:
      warehouse:
        type: string
        description: Склад оргранизации
        enum:
          - Moscow
          - SPB
      organizationInn:
        type: string
        description: ИНН оргранизации(Юркас)
      counterpartyInn:
        type: string
        description: ИНН
      messageNumber:
        type: integer
        format: int64
        description: Номер входящего сообщения. Уникальный номер клиентской заявки.
      tradePointUID:
        $ref: '#/definitions/tradePointUID'
      formOfPayment:
        $ref: '#/definitions/formOfPayment'
      goods:
        type: array
        items:
          $ref: '#/definitions/goods'
    required:
      - warehouse
      - organizationInn
      - counterpartyInn
      - messageNumber
      - tradePointUID
      - formOfPayment
      - goods
  status:
    title: Статус заказа
    type: object
    properties:
      NumberOrder:
        type: integer
        format: int64
        description: Номер заявки в базе Юркас.
      Status:
        $ref: '#/definitions/statuses'
  statuses:
    title: Статусы заказа
    type: string
    description: |
      * `accepted` --- Заказ принят в обработку
      * `paymentExpected` --- Заказ ожидает оплату (Заказные позиции)
      * `inprogress` --- Заказ находиться в работе
      * `ready` --- Заказ готов к отгрузке
      * `closed` --- Заказ закрыт
      * `completed` --- Заказ выполнен
    enum:
      - accepted
      - inprogress
      - ready
      - closed
      - completed
  goods:
    title: Таблица товаров
    type: object
    properties:
      barcode:
        type: string
        description: Штрихкод
      name:
        type: string
        description: >-
          Наименование в формате :((Код)) + Наименование
          Например: ((00011111)) Добор под U 100*2440 Манхэттен 
          Код и наименование в вашей базе.
      count:
        type: integer
        format: int64
    required:
      - count
  formOfPayment:
    title: Форма расчетов
    type: string
    description: |
      * `NAL` --- оплата наличными
      * `BNAL` --- безналичная форма оплаты
    enum:
      - NAL
      - BNAL
  responsePrice:
    title: Ответ на getPrice
    type: object
    properties:
      NumberOrder:
        type: integer
        format: int64
        description: Номер заявки в базе Юркас.
      Status:
        $ref: '#/definitions/statuses'
      goods:
        $ref: '#/definitions/goods' 
  tradePointUID:
    type: string
    title: UID торговой точки
    description: >-
      UID торговой точки, необходимо получить у тех. специалиста.
