swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Yurkas order"
host: "localHost"
basePath: "/v1"
tags:
- name: "Access orders"
  description: "Доступ к заказам"
schemes:
- "http"
paths:
  /order:
    post:
      tags:
      - "Access orders"
      summary: "Создать заказ"
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Размещение заказа"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "201":
          description: "CREATED"
          schema:
            $ref: "#/definitions/status"
        "400":
          description: "Bad Request"
  /order/{MessageNumber}/{counterpartyInn}:
    get:
      tags:
      - "Access orders"
      summary: "Получить статус заказа"
      operationId: "getOrderById"
      produces:
      - "application/json"
      parameters:
      - name: "MessageNumber"
        in: "path"
        description: "Номер заказа по которому нужно получить статус"
        required: true
        type: "integer"
        format: "int64"
      - name: "counterpartyInn"
        in: "path"
        description: "ИНН контрагента"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/status"
        "400":
          description: "Bad Request"
        "404":
          description: "Order not found"
definitions:
  Order:
    title: "Заказ"
    type: "object"
    properties:
      warehouse:
        type: "string"
        description: "Склад оргранизации"
        enum:
        - "Moscow"
        - "Spb"
      organization:
        type: "string"
        description: "Название оргранизации"
        enum:
        - "Yurkas"
        - "Germes"
        - "YurkasSpb"  
      counterpartyInn:
        type: "string"
        description: "ИНН"
      MessageNumber:
        type: "integer"
        format: "int64"
        description: "Номер входящего сообщения. Уникальный номер клиентской заявки."
      tradePoint:
        type: "string"
        description: "Кординаты торговой точки в формате [53.848776, 27.372260] [Широта, долгота]"
      formOfPayment:
        type: "string"
        description: "Форма расчетов"
        enum:
        - "NAL"
        - "BNAL"
      goods:
        $ref: "#/definitions/goods"
    xml:
      name: "Order"
  status:
    title: "Статус заказа"
    type: "object"
    properties:
      status:
        type: "string"
        description: "Статус заказа"
        enum:
        - "accepted"
        - "inprogress"
        - "closed"
        - "completed"
    xml:
      name: "status"
  goods:
    title: "Таблица товаров"
    type: "object"
    properties:
      barcode:
        type: "string"
        description: "Штрихкод"
      count:
        type: "integer"
        format: "int64"
    xml:
      name: "goods"